# Generated by Django 5.0.6 on 2024-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poste_type',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
