# Generated by Django 5.0.6 on 2024-05-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_poste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poste_type',
            field=models.CharField(default='NA', max_length=2),
        ),
    ]
